### ISSUE TITLE
Update releases.json path

### ISSUE THREAD

**Issue by steveooo9** [lewiscommunications/craft-presto#12]
Hello,

it seems that Craft 2 doesn't find the releases.json feed anymore after changing the things from /master/ to /craft-2.5/. Simply update:

```
	public function getReleaseFeedUrl()
	{
		return 'https://raw.githubusercontent.com/lewiscommunications/craft-presto/craft-2.5/releases.json';
	}
```

I am talking about the craft 2.5 version.. Thanks!

**Comment by steveooo9** [comment]
@peterbedor Could you do this?

**Comment by peterbedor** [comment]
Sorry for the delay!
