### ISSUE TITLE
Undefined offset 1 - not breaking cache

### ISSUE THREAD

**Issue by lealea** [lewiscommunications/craft-presto#4]
Whenever I try to save an entry it gives me this error:

`Undefined offset: 1
`
And specifically cites Line 120:

`str_replace('home', '', $url[1])
`
Changing it to [0] removes the error but it doesn't break the cache.

**Comment by ryanbrookepayne** [comment]
@lealea Try purging your entire cache in the settings page. Looks like there is a mixture of native craft and presto template caching keys which is causing the index issue.

See this issue for more information: https://github.com/caddis/craft-presto/issues/18.

Let me know if that works.

**Comment by lealea** [comment]
Hi @ryanbrookepayne — it worked and then it didn't. It worked in the first initial build. Then when I went back into the entry to do another edit, it had the error again. Right now I'm just testing the plugin on a staging server to see how it all works so the page has some native cache items internally. I wrapped Presto cache on the MAIN template, but stuff like the interior main nav/footer has native cache on there. But regardless, that shouldn't affect things, right? It just seems weird it would?

**Comment by ryanbrookepayne** [comment]
@lealea try removing the native cache tags and clearing the entire cache again. Presto is not meant to work in conjunction with the native craft cache tags since you serve a static html file once the page is loaded.

**Comment by lealea** [comment]
HI @ryanbrookepayne — that worked. Thanks for providing this awesome plugin. Client is thrilled. :) Can't wait until the roadmap items get checked off.

**Comment by ryanbrookepayne** [comment]
@lealea no problem! Glad to help.
