### ISSUE TITLE
Clearing Presto Cache Causes Homepage 404

### ISSUE THREAD

**Issue by lealea** [lewiscommunications/craft-presto#5]
This is a very strange issue and only seems to happen intermittently. Do note that my client's site is on IIS so it's possible that is an issue here but I also think that there's a check failing in the plugin.

Long story short:

- Clearing Presto Cache via CP sometimes causes the homepage to 404. Sometimes (not always) this happens if someone manually deletes a file/folder in /cache. Sometimes (maybe?) it happens if someone is still clicking around the site and clears Presto cache at the same time.
- Refreshing the domain.com won't re-create the homepage, as it strangely still tries to find the index.html
- Visiting domain.com/index.php recreates the homepage as expected though — this is our basic workaround at the moment after a full site cache clear

Here's the Craft log that basically gives an internal server error. After refreshing the CP when it gives that error, it tries to clear the cache again and sometimes that triggers the 404.

This ONLY happens on the homepage and only really after cache clearing. Deleting inside pages or even the index.html manually and refreshing the page, regenerates the page as expected.

```
2017/11/27 20:50:19 [error] [php] rmdir(D:/websites/domain.com_stage/public/cache/staging.domain.com/): Directory not empty (D:\websites\domain.com_stage\craft\app\helpers\IOHelper.php:1385)
Stack trace:
#0 D:\websites\domain.com_stage\craft\app\helpers\IOHelper.php(1308): deleteFolder()
#1 D:\websites\domain.com_stage\craft\plugins\presto\services\PrestoService.php(148): clearFolder()
#2 D:\websites\domain.com_stage\craft\plugins\presto\controllers\PrestoController.php(20): Craft\PrestoService->purgeEntireCache()
#3 D:\websites\domain.com_stage\craft\app\framework\web\actions\CInlineAction.php(49): Craft\PrestoController->actionPurgeCache()
#4 D:\websites\domain.com_stage\craft\app\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\websites\domain.com_stage\craft\app\framework\web\CController.php(286): Craft\PrestoController->runAction()
#6 D:\websites\domain.com_stage\craft\app\framework\web\CController.php(265): Craft\PrestoController->runActionWithFilters()
#7 D:\websites\domain.com_stage\craft\app\framework\web\CWebApplication.php(282): Craft\PrestoController->run()
#8 D:\websites\domain.com_stage\craft\app\etc\web\WebApp.php(823): Craft\WebApp->runController()
#9 D:\websites\domain.com_stage\craft\app\etc\web\WebApp.php(287): Craft\WebApp->_processActionRequest()
#10 D:\websites\domain.com_stage\craft\app\framework\base\CApplication.php(185): Craft\WebApp->processRequest()
#11 D:\websites\domain.com_stage\craft\app\index.php(62): Craft\WebApp->run()
#12 D:\websites\domain.com_stage\public\index.php(38): require_once()
REQUEST_URI=/index.php/admin/actions/presto/PurgeCache
```

Any insight or fix would help!

It's just so odd that visiting index.php will auto-regenerate the homepage but without it, when the cache clears, it doesn't recreate it AND a server-side (not even Craft) 404 shows because index.html doesn't exist.

**Comment by ryanbrookepayne** [comment]
@lealea What is "IIS"? Are you using apache or nginx?

**Comment by lealea** [comment]
@ryanbrookepayne We're running Craft and PHP on a Windows server (college client; can't move hosting)

**Comment by ryanbrookepayne** [comment]
@lealea I don't have any experience with Windows servers. However, there seems to be something wrong with your configuration. The [Apache and Nginx configuration guides](https://github.com/lewiscommunications/craft-presto#step-3---configure-your-server) show how to check for the static html file. If the static file does not exist, the index.php file is served (similar to what you are doing). You can't assume that the static html file will always exist.

**Comment by ryanbrookepayne** [comment]
@lealea This guide may help you: https://www.iis.net/learn/application-frameworks/install-and-configure-php-applications-on-iis/translate-htaccess-content-to-iis-webconfig.

**Comment by lealea** [comment]
@ryanbrookepayne That's exactly it. It's supposed to serve the index.php if the static file doesn't exist. But it doesn't. We did essentially translate what you had and it _works_ except in the case of the FULL Presto cache clearing.

```
<rule name="Check for static file in /cache dir" stopProcessing="true">
    <match url=".*" />
    <conditions logicalGrouping="MatchAll" trackAllCaptures="false">
        <add input="{REQUEST_FILENAME}" pattern="\.(css|eot|gif|ico|jpe?g|otf|png|svg|ttf|webp|woff2?)$" negate="true" />
        <add input="{REQUEST_METHOD}" pattern="GET" />
        <add input="{DOCUMENT_ROOT}/cache/{HTTP_HOST}/presto/{REQUEST_URI}/index.html" matchType="IsFile" />
    </conditions>
    <action type="Rewrite" url="/cache/{HTTP_HOST}/presto/{REQUEST_URI}/index.html" appendQueryString="true" logRewrittenUrl="true" />
</rule>
```

And it's above the Craft remove index.php item

**Comment by lealea** [comment]
Adding note that inside pages still all render just fine when you visit it without index.php. Everything works _except_ full cache clearing the homepage. It somehow fails then. :-/

**Comment by ryanbrookepayne** [comment]
@lealea It appears that you may need to make an adjustment to your config file specific to the homepage. I wish I could help you but I don't have the experience with Windows servers to debug the issue further. I'm going to close out this issue as it's not actually an issue with Presto. Let me know what you find out.
