### ISSUE TITLE
Craft 3 Version

### ISSUE THREAD

**Issue by maxstrebel** [lewiscommunications/craft-presto#7]
Hi there, I'm a frequent user and wanted to ask if you plan to Port this to Craft 3?

Thanks!

**Comment by ryanbrookepayne** [comment]
@maxstrebel [Craft Static](https://github.com/buzzingpixel/craft-static) might be a good option for you.

**Comment by maxstrebel** [comment]
@ryanbrookepayne Thanks for your Answer, I'll check it out! Just to close this, no plans for a Port?

**Comment by ryanbrookepayne** [comment]
@maxstrebel I am not sure about the port. I'm no longer on the team that maintains this plugin.

**Comment by peterbedor** [comment]
@maxstrebel Hey, sorry for the delay.  We're currently working on the Craft 3 port and should be ready for release in the next two weeks.

**Comment by peterbedor** [comment]
@maxstrebel I've merged the port into master, though it's still in beta.  We'll be releasing it to the plugin store when we're finished with everything.  Thanks again.

**Comment by maxstrebel** [comment]
@peterbedor this is great, thank you so much. In case I can help with testing or anything else, let me know.

**Comment by peterbedor** [comment]
@maxstrebel Will do.  We recently discovered a bug with pagination, where Presto will only ever serve up the first page results.  I'll be looking into it, but just wanted to let you know.  Unsure of when the update will be exactly, but soon.

**Comment by chasegiunta** [comment]
@peterbedor Any update on this? You mentioned that the master branch is update for Craft 3. Will it be on the plugin store?
