### ISSUE TITLE
Error thrown when using Presto with other caching (with FIX!)

### ISSUE THREAD

**Issue by steveooo9** [lewiscommunications/craft-presto#8]
When using the other cache tags together when having Presto not being active everywhere but more on a per page basis, the script throws an error. Issue is that there are other cached items in `craft_templatecache` that don't have `|` as a key. So I tested it and found a fix that prevents unnecessary file checks by using exiting early. I am unable to do pull request, so please add this fix officially:

Add
```
if (count($url) < 2) {
  continue;
}
```
on line `113` between `$url` and `$targetPath`.

Here is the error:
```
Undefined offset: 1

/var/www/craft/plugins/presto/services/PrestoService.php(120)

108     public function purgeCache($paths = [])
109     {
110         if (count($paths)) {
111             foreach ($paths as $path) {
112                 $url = explode('|', $path, 2);
113 
114                 $targetPath = IOHelper::folderExists(
115                     $this->normalizePath(implode('/', [
116                         $this->rootPath,
117                         $this->settings->cachePath,
118                         $url[0],
119                         'presto',
120                         str_replace('home', '', $url[1])
121                     ]))
122                 );
123 
124                 $targetFile = IOHelper::fileExists($targetPath . '/index.html');
125 
126                 if ($targetFile) {
127                     @unlink($targetFile);
128                 }
129 
130                 if ($targetPath) {
131                     @rmdir($targetPath);
132                 }```

**Comment by steveooo9** [comment]
@ryanbrookepayne Can you add this change and release this as a fix? Thank you!

**Comment by ryanbrookepayne** [comment]
@steveooo9 Hey Steve, I am no longer on the team that manages this code.

**Comment by steveooo9** [comment]
@ryanbrookepayne Do you know who is?

**Comment by steveooo9** [comment]
Anyone?

**Comment by peterbedor** [comment]
Hey @steveooo9, thanks for this.  I'm updating it now and should be pushing it up soon.
